[package]
name = "layout_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
serde_json = "1.0"
lazy_static = "1.4"
utf8-read = "0.4.0"
rayon = "1.6.1"
toml = "0.7.2"
